version: '3.8'

services:
  CodeCompiler:
    image: postgres:latest
    restart: no
    container_name: CodeCompiler
    volumes:
      - volumename:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=CodeCompiler
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456

volumes:
  volumename: